package com.pv239.brnotouristapp.district

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData

class DistrictRepository {

    private val _districtList = MutableLiveData<List<District>>()
    val districtList: LiveData<List<District>> = _districtList

    fun loadDistricts() {
        val exampleDistricts = listOf(
            District(
                "Střed",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-st%C5%99ed_vlajka.svg",
                49.194167,
                16.608611
            ),
            District(
                "Sever",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-sever_vlajka.svg",
                49.215,
                16.626389
            ),
            District(
                "Jih",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-jih_(vlajka).svg",
                49.1745,
                16.6228
            ),
            District(
                "Bohunice",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Bohunice_(vlajka).svg",
                49.169444,
                16.579167
            ),
            District(
                "Bosonohy",
                "https://commons.wikimedia.org/wiki/Category:Brno-Bosonohy#/media/File:Brno-Bosonohy_(vlajka).svg",
                49.176111,
                16.529167
            ),
            District(
                "Bystrc",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Bystrc_-_flag.svg",
                49.224722,
                16.523889
            ),
            District(
                "Chrlice",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Chrlice_vlajka.svg",
                49.134167,
                16.652778
            ),
            District(
                "Ivanovice",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Ivanovice_vlajka.svg",
                49.264722,
                16.564722
            ),
            District(
                "Jehnice",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Flag_of_Brno-Jehnice.svg",
                49.271111,
                16.596111
            ),
            District(
                "Jundrov",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Vlajka_Brno-Jundrov.svg",
                49.207778,
                16.555278
            ),
            District(
                "Kníničky",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Kn%C3%ADni%C4%8Dky_vlajka.svg",
                49.236111,
                16.527778
            ),
            District(
                "Kohoutovice",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Kohoutovice_vlajka.svg",
                49.1933,
                16.5369
            ),
            District(
                "Komín",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Kom%C3%ADn_vlajka.svg",
                49.220556,
                16.554167
            ),
            District(
                "Královo Pole",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Kr%C3%A1lovo_Pole_vlajka.svg",
                49.223611,
                16.594444
            ),
            District(
                "Líšeň",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-L%C3%AD%C5%A1e%C5%88_vlajka.svg",
                49.2075,
                16.6861
            ),
            District(
                "Maloměřice a Obřany",
                "ttps://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Malom%C4%9B%C5%99ice_a_Ob%C5%99any_vlajka.svg",
                49.223889,
                16.643889
            ),
            District(
                "Medlánky",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Medl%C3%A1nky_vlajka.svg",
                49.241667,
                16.573889
            ),
            District(
                "Nový Lískovec",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Nov%C3%BD_L%C3%ADskovec_vlajka.svg",
                49.177778,
                16.559444
            ),
            District(
                "Ořešín",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_Brno-O%C5%99e%C5%A1%C3%ADn#/media/File:Flag_of_Brno-O%C5%99e%C5%A1%C3%ADn.svg",
                49.276667,
                16.607222
            ),
            District(
                "Slatina",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Slatina_vlajka.svg",
                49.178333,
                16.684722
            ),
            District(
                "Starý Lískovec",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-Star%C3%BD_L%C3%ADskovec_vlajka.svg",
                49.169167,
                16.562222
            ),
            District(
                "Tuřany",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Flag_of_Brno-Tu%C5%99any.svg",
                49.1472,
                16.6631
            ),
            District(
                "Vinohrady",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Flag_of_Brno-Vinohrady.gif",
                49.2058,
                16.6583
            ),
            District(
                "Útěchov",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-%C3%9At%C4%9Bchov_vlajka.svg",
                49.287222,
                16.631111
            ),
            District(
                "Černovice",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-%C4%8Cernovice_(vlajka).svg",
                49.182778,
                16.636944
            ),
            District(
                "Řečkovice a Mokrá Hora",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-%C5%98e%C4%8Dkovice_a_Mokr%C3%A1_Hora_vlajka.svg",
                49.2525,
                16.5825
            ),
            District(
                "Žabovřesky",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-%C5%BDabov%C5%99esky_vlajka.svg",
                49.214444,
                16.575278
            ),
            District(
                "Žebětín",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Flag_of_Brno-%C5%BDeb%C4%9Bt%C3%ADn.svg",
                49.206944,
                16.487778
            ),
            District(
                "Židenice",
                "https://commons.wikimedia.org/wiki/Category:Flags_of_city_districts_of_Brno#/media/File:Brno-%C5%BDidenice_vlajka.svg",
                49.196111,
                16.6475
            )
        )
        _districtList.value = exampleDistricts
    }
}